### ISSUE TITLE
Software manager UX experience

### ISSUE THREAD

**Issue by edap** [ubuntu/desktop-devel-feedback#3]
Hello everybody, I am reporting a minor issue for the user interface of ubuntu 22.04, apparently an issue 3 years old https://discourse.ubuntu.com/t/rename-software-updater-and-software-updates/14757. I do not think it is very welcoming for beginners users to have a lot of options when they search for the word “software”,
![Screenshot from 2023-06-19 11-00-49](https://github.com/ubuntu/desktop-devel-feedback/assets/161152/a34bc3f5-6028-4769-a207-2265d16b859c)

My problems with this interface can be summarized with two questions:

-  I do see an app appearing two times. Why?
-  It looks like all the 4 apps are doing the same thing, managing the installed software. And for managing I mean update, install and remove. What is the difference between them? why Ubuntu needs 4 apps to do this? Which one should I use?

I would expect to find just one app that does the job of installing, upgrading and deleting software (good old times when synaptic was considered to be cool! ), and this app takes care of the system packages installed through apt, the drivers (proprietary drivers included), and the "user space" packages installed through snap.

**Comment by tim-hm** [comment]
Hi @edap, thanks for your feedback! We are actively working to (mostly) resolve this for 23.10. But there are several layered issues here to discuss.

1. The plan for 23.10 is a new "App Store" which does the job of managing (mostly) GUI applications. It will be snap first but will support debs as well. We're in the middle of designing this and expect to release more information at the next pulse roundup (due ivo Friday 29 June 23). Would love to hear your thoughts on that when its ready to share :pray: 

2. We are going to tweak names/keywords (and potentially icons) for `Software Updater` and `Software & Updates` for 23.10 with the aim to better communicate what each one does (check for updates vs configure update checking, former and later respectively).

3. Wrt your 2x "Ubuntu Software" and "Software" search results in your screenshot. Thats odd .. have a installed `gnome-software` (white icon)? I'm not sure whats happening with the 2x Ubuntu Software results. You could check in `$XDG_DATA_DIRS/applications` and see if there are mostly duplicate launcher files. I saw mostly because the behaviour I experience locally is in the case of a duplicate (as in identical) only one is shown. I can't spin up 22.04 just now, so will have to circle back and check. @seb128 any thoughts?

4. Longer term, I have some preliminary plans to folding "Software & Updates" into Settings (as well as the Language launcher). We won't have capacity this cycle and so I'm aiming to do 1 and 2 above until we do (hoping for 24.40).

Okay so quiet a few bits there but hopefully a much better experience from 23.10 forward. That doesn't exactly help you on 22.04 though as its a bit harder back porting these larger changes to an LTS.

WDYT?

cc @anasereijo @elioqoshi

**Comment by edap** [comment]
Many thanks for this detailed reply, I really appreciate it. I will add my observations here. Regarding point 1, popOS! already did it, they have a "pop shop" where you can manage all the flahub application, the debs packages and the system software updates, in my experience is far from perfect, but maybe it is worth to have a look into it, as it is an ubuntu based distro.

For point 2) I personally do not think that the distinction between configuring the software updater and apply software updates should be visible to the user outside of the "software manager" app. I think this app should be the central place where a user manage the installed software, and it has its own settings where a user can, for example, configure the frequency of the update checks.

About point 3, I am sure I did not add the desktop entry for the software app by myself, and I am also sure that this issue is old, it was more present in the past releases, now it has been partially mitigated, but I clearly remember the times where i was looking for an app and two icons for the same apps appeared. But thanks for the tips, I will try to remove the duplication following your suggestions.

For the long term perspective, after almost 20 years on Linux, what I can say about the software manager is that all the distros are trying to avoid the Big Problem, they are all trying shortcuts to avoid to deal with it. In my opinion the Big Problem (beside UX design) is that there is no clear distinction between user apps and system software, and this problem has consequences visible also in the surface, like in the UX design of the software manager app. I do think that system software is what define your operating system as such, it should have a clear and defined API, with clear and defined boundaries. And aptitude is a great piece of software to manage this kind of system. System software is what makes a bottom base system. User apps, on the other side, should talk to this system API, and they should do it isolated inside something similar to jails in freebsd.
Refusing to deal directly with this problem will lead to failure anyway, and I think that Snap and Flathub are not the solution, they are workarounds. This last point is just my personal opinion about the sofware problem, and it has nothing to do with the issue posted, but as you were talking about long term perspective I feel to add my thoughts.

**Comment by seb128** [comment]
Re 3. I don't have a better idea than your guess Tim, the white icon is probably because the gnome-software deb has been installed. The duplicated Ubuntu Software is weird, grepping for the string in $XDG_DATA_DIRS/applications 

```
$ for dir in `echo $XDG_DATA_DIRS | tr ':' ' '`; do grep Software $dir/applications/*.desktop | grep Name=; done
```

**Comment by tim-hm** [comment]
> there is no clear distinction between user apps and system software

Agreed. I don't think the settings for system software updates should be defined in an App Store because system software to me isn't an "app" from a users perspective. At the same time I don't want to split these settings into multiple locations and I don't think a separate "Would you like to apply these updates" prompt is necessary. What I'd like to do is something like this:

1. System wide update settings => Settings (cadence, base OS 'track', sources, keys, etc)
2. App Store => install/update/remove user facing applications
3. A better updater prompt that surfaces updates across the whole system and groups them roughly as (terms tbc): Hardware (ie firmware), OS, User.

As I said all preliminary but I think we want to head in this direction.

**Comment by hifron** [comment]
According search on packages.ubuntu.com for [software-properties-gtk.desktop](https://packages.ubuntu.com/search?suite=mantic&arch=any&mode=exactfilename&searchon=contents&keywords=software-properties-gtk.desktop) in same named packages content there are four packages with this file and one of them(4) is:
[software-properties-gtk](https://packages.ubuntu.com/mantic/software-properties-gtk) which could be listed which files has for some architectures(in this case any arch) which could be seen which files in this package are installed on disk [files in this package](https://packages.ubuntu.com/mantic/all/software-properties-gtk/filelist) like:

```
/usr/share/applications/software-properties-drivers.desktop
/usr/share/applications/software-properties-gtk.desktop
/usr/share/applications/software-properties-livepatch.desktop
```
and file software-properties-drivers.desktop and software-properties-gtk.desktop differs only with open-tab=4 execution attribute, but there is also [update-manager.desktop in 2 packages](https://packages.ubuntu.com/search?suite=lunar&arch=any&searchon=contents&keywords=update-manager.desktop) and one of them [has such update-manager desktop file on disk](https://packages.ubuntu.com/lunar/update-manager) with result of 2 icons doing the same in GNOME.

In icon management there is possibility to hide it in some desktop environment or maybe also to show it in some environments. The former should be done with alacarte package when on some system application it is deleted on user(not only deselected) and then it is in ~/.local/share/application created alacarte menu entry desktop file with option hidden meaning that such application is not listed for such user(but he can create another one with maybe other options with same icon)...

**Comment by hifron** [comment]
[Similar Discourse question](https://discourse.ubuntu.com/t/snap-parallel-install-create-desktop-entry-automatically/36335) for Steam and Steam Beta snap

**Comment by tim-hm** [comment]
Perhaps we've gone slightly off piste from OP.

We've made progress this cycle from multiple 'Software' results with the App Center and Firmware Updater. I have a longer term goal to further improve this but I think for now we can resolve this issue?
