### ISSUE TITLE
Full Disk Encryption

### ISSUE THREAD

**Issue by ibahnasy** [ubuntu/desktop-devel-feedback#5]
### Description

Nowadays a full disk encryption that includes the entire disk (including /boot) is a must, not just the root or home filesystems.

### Negatives

The purpose of full disk encryption is to protect data in case of physical disk access.
Currently the disk encryption option in Ubuntu only encrypts the / root filesystem including /home and leaves /boot un-encrypted, which is fine if the attacker is just trying to copy the data on disk.

But that's not only the threat, an attacker could modify the kernel or initramfs files on a plain /boot partition with a rootkit or malware then when the user boots his system, the whole system and user's passwords are compromised and data can be transferred remotely or physically  and the attacker has full root access to that system.
Suggestions for Improvement

### Suggestions for Improvement

Debian 12 already supports the encryption of the entire disk in their installer, only leaves the EFI partition plain of course.
In this case it uses LUKS1 which is supported by older Grub versions.
It works if you select manual partitioning and created a plain EFI partition and an encrypted / root filesystem without creating a separate /boot partition. 

Currently Grub 2.12 I think supports LUKS2 which  is shipped in Ubuntu 23.10.

Encryption of /boot should be out of the box or by an option in the Ubuntu installer.

### Hardware Specifications

Any laptop or desktop computers.

**Comment by jibel** [comment]
Thanks for your report.

Full Disk Encryption (FDE) leveraging the TPM capabilities of the platform is landing in Ubuntu 23.10.
This [blog post](https://ubuntu.com/blog/tpm-backed-full-disk-encryption-is-coming-to-ubuntu) describes the solution implemented on Ubuntu Desktop.

**Comment by ibahnasy** [comment]
If I understand correctly about the new TPM feature, the LUKS passphrase will be stored into the TPM module and on boot it will automatically unlock the encrypted volume.

If that is how it works then this is really not a security enhancement over manually typing the passphrase, because TPM is accessible via the BIOS / UEFI firmware and most of them only support short alphanumeric passwords.
Another weakness is that most of those firmware support default manufacturer password or code to login if the firmware is locked due to wrong login trials, even there are Android apps that generate the default codes based on the error code you get after the firmware is locked out.

A more secure way is to store the LUKS encryption key (not passphrase) on a USB stick, or even make that stick encrypted by a passphrase, then it provides the key.

The most secure way is to support U2F hardware keys like the "Yubikey".

But really /boot must be a part of the encrypted volume!

**Comment by tim-hm** [comment]
> TPM is accessible via the BIOS / UEFI firmware and most of them only support short alphanumeric passwords

Correct, the TPM can be accessed via the BIOS / UEFI, but it's important to clarify that the passphrase cannot be extracted from the TPM module. The only action available from the firmware level is to clear the TPM, thereby making the encrypted data inaccessible.

> Another weakness is that most of those firmware support default manufacturer password or code to login if the firmware is locked due to wrong login trials

A malicious actor with the capability to access BIOS / UEFI settings could indeed clear the TPM, but that would render the data on the disk inaccessible rather than compromised, assuming a recovery key isn't available.

> even make that stick encrypted by a passphrase

While using an encrypted USB stick for the LUKS key is an option, it brings its own set of challenges. Requiring external hardware for booting introduces an additional point of failure and might not align well with the threat model for the majority of users. Our approach with TPM-backed Full Disk Encryption aims for a balanced trade-off between security and convenience. The TPM will only release the encryption keys if the boot process integrity is maintained, providing a sufficiently secure solution for most use cases.

There are a few additional advantages with the TPM approach which are worth raising. Firstly, if there are multiple users on the machine TPM backed FDE means there is no need to introduce multiple external devices which bring their own risks. Secondly, this solution is ideal in an enterprise setting where the machine can boot to the login screen, establish a network connection and then allow for administrators to continue ... administering.

Many thanks for your comment 🙏
